### ISSUE TITLE
no use of injectors

### ISSUE THREAD

**Issue by larshp** [abapGit/CI#10]
All abapGit APIs should at some point work without requiring GUI, if not it has to be changed/fixed.

So there should be no use of injectors in this project

**Comment by larshp** [comment]
there is still a call to `zcl_abapgit_ui_injector=>set_gui_functions( NEW lcl_mock_ui_functions( ) ).`,
https://github.com/abapGit/CI/blob/6a9be341e254d3654d2a9f9e425ff9dd48ba6e63/src/zcl_abapgit_ci_repo.clas.abap#L124

I have not looked into the details. This is just something we need to look into sometime

**Comment by christianguenter2** [comment]
yeah, that one is needed, because otherwise we geed the a lot of nasty activation popups when running online.
https://github.com/larshp/abapGit/pull/2039

**Comment by mbtools** [comment]
no more injectors. closed by https://github.com/abapGit/CI/pull/244
