### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by albertmink** [abapGit/CI#179]
Might be similar to https://github.com/abapGit/abapGit/issues/5565

Report crashes, see
![image](https://user-images.githubusercontent.com/38354196/181772127-ea4756e5-402e-458d-bb85-1a8ddf5e8e89.png)

**Comment by larshp** [comment]
https://github.com/abapGit/CI/blob/f75fad223ac8063bd12160401073118df2d82417/src/zcl_abapgit_ci_repo_category.clas.abap#L243-L262

does database table `rstlogoprop` exist in your system?

**Comment by albertmink** [comment]
`rstlogoprop` does not exist

**Comment by larshp** [comment]
hmm, guess it would be easier if the `c_category_bw` was hardcoded

guess the types are listed at https://ci.abapgit.org/src/0242ac1100021eebb1bbc829fae4fe35.smim.abapgit_ci_result.html#business_warehouse
