### ISSUE TITLE
also run normal unit tests?

### ISSUE THREAD

**Issue by larshp** [abapGit/CI#33]

**Comment by christianguenter2** [comment]
abapGit unit tests are already executed, or do mean somethink else?
![grafik](https://user-images.githubusercontent.com/17437789/48868277-4cfaef80-edd9-11e8-819a-cd4817e5e548.png)

**Comment by larshp** [comment]
oh, would like an overview then, one line for each test, its difficult to see what is run or fails with just yes/no

**Comment by christianguenter2** [comment]
ok, if the unit test faills the error message should be quite descriptive. But you are right an overview would be nice.
