### ISSUE TITLE
run CI for open PRs

### ISSUE THREAD

**Issue by larshp** [abapGit/CI#45]

**Comment by larshp** [comment]
can use https://github.com/abapGit/abap_git_hosts_apis to find the list of open PRs, plus add comments to the PRs

**Comment by mbtools** [comment]
Do you mean PRs of abapGit? I'm not sure how this could work. CI depends on the AG dev version. If we fetch a PR, it would probably overwrite some classes that CI uses to run the tests.

**Comment by larshp** [comment]
yea, closing
