### ISSUE TITLE
Parameter in ZABAPGIT_CI report to control the purge

### ISSUE THREAD

**Issue by gregorwolf** [abapGit/CI#78]
Using ZABAPGIT_CI is a great way to install quickly all abapGit supported development artefacts. But as quickly as their installed, they are also deleted (purged). That is triggered in the RUN method of ZCL_ABAPGIT_CI_REPO. 

What do you think about a parameter in the ZABAPGIT_CI report to control the purge. I.e.:

[ ] Don't purge the installed packages

**Comment by larshp** [comment]
no problem from my POV

**Comment by gregorwolf** [comment]
I would add a field DO_NOT_PURGE to the structure ZABAPGIT_CI_RESULT so that I can bring the information from the report to the method.
