### ISSUE TITLE
Skip on higher version required

### ISSUE THREAD

**Issue by larshp** [abapGit/CI#8]
Something like https://github.com/abapGit-tests/BDEF will require SAP BASIS 773.
This will be specified in the .abapgit.xml, and as normal abapGit will check version requriements.
In case a higher version is required, the CI should skip the repo.

**Comment by mbtools** [comment]
We have to clone+pull first, before we can evaluate abapgit.xml and skip.

Did #94 close this or should we suppress the error and set the status to "ok"?
