### ISSUE TITLE
Syntax error in zcl_abapgit_ci_repos

### ISSUE THREAD

**Issue by pokrakam** [abapGit/CI#81]
Refactoring in abapGit renamed method set_branch_name

PR on way, but I can't create a branch or assign myself. Will do via fork.

**Comment by larshp** [comment]
thanks

I've added you to the project

I've also added "abapGit/CI" to regression test of https://github.com/abaplint/abaplint/pull/1508 which I run quite often

on longer term there will be a setup to somehow discover breaking changes across repos

**Comment by pokrakam** [comment]
Thanks, PR created. I note the linter has been improved since this was last changed so needs a few more updates.

**Comment by larshp** [comment]
two errors remain, see https://github.com/abapGit/CI/pull/83

I think those two should be fixed, but I wont do it today, pull requests welcome
